[features]
seeds = false
skip-lint = false
[programs.localnet]
counter = "GV1YdRuFLtfzvYpdY2aGQJpWDi6NQhx7svDH9w59MQdz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sandeep/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
